name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build image
        run: bash bin/build

      - name: Display all docker images
        if: ${{ always() }}
        run: docker images

      - name: Login to Docker Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          # We push to the default registry currently. If you want to push to a different registry,
          # uncomment the line below.
          # login-server: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REG_USERNAME }}
          password: ${{ secrets.DOCKER_REG_PASSWORD }}

      - name: Push image
        if: github.ref == 'refs/heads/main'
        run: bash .github/scripts/push-image.sh
        env:
          DOCKER_USER: ${{ secrets.DOCKER_REG_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_REG_PASSWORD }}
