name: Test

on:
  push:
    branches:
      - main
      - renovate/**

  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2

      - name: Run build with tests
        run: bash bin/build
