name: Test

on:
  push:
    branches:
      - main
      - renovate/**

  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          name: ambimax/testrepo-semantic-composer-releases
          path: testrepo-semantic-composer-releases

      - name: Run build with tests
        run: |
          ssh -vT git@github.com
          bash bin/build
        env:
          GITHUB_TOKEN: ${{ secrets.AMBIMAX_GITHUB_RELEASE_TOKEN }}
